<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dnlib" Version="4.5.0" />
    <PackageReference Include="K4os.Compression.LZ4" Version="1.3.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bin2Object\Bin2Object.csproj" />
    <ProjectReference Include="..\VersionedSerialization.Generator\VersionedSerialization.Generator.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    <ProjectReference Include="..\VersionedSerialization\VersionedSerialization.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Outputs\ScriptResources\shared_base.py" LogicalName="Il2CppInspector.Outputs.ScriptResources.shared_base.py" />
    <EmbeddedResource Include="Outputs\ScriptResources\Targets\BinaryNinja.py" LogicalName="Il2CppInspector.Outputs.ScriptResources.Targets.BinaryNinja.py" />
    <EmbeddedResource Include="Outputs\ScriptResources\Targets\Ghidra.py" LogicalName="Il2CppInspector.Outputs.ScriptResources.Targets.Ghidra.py" />
    <EmbeddedResource Include="Outputs\ScriptResources\Targets\IDA.py" LogicalName="Il2CppInspector.Outputs.ScriptResources.Targets.IDA.py" />
  </ItemGroup>
</Project>
