using System.Globalization;
using System.Text;
using Il2CppInspector.Cpp.UnityHeaders;
using Il2CppInspector.Model;
using Il2CppInspector.Reflection;

namespace Il2CppInspector.Outputs
{
    // Stream layouts straight from metadata, retaining only a small dependency traversal.
    internal sealed class ZzzHeaderWriter(AppModel model, bool useBetterArraySize)
    {
        private ZzzMorax Adapter => (ZzzMorax)Package.Metadata.GameAdapter;

        private ZzzNativeModel native => (ZzzNativeModel)model.GameNativeModel;
        private UnityHeaders headers => model.UnityHeaders;
        private static readonly HashSet<string> FieldKeywords = new(
            (
                "alignas alignof and and_eq asm atomic_cancel atomic_commit atomic_noexcept auto bitand bitor bool break case catch char "
                + "char8_t char16_t char32_t class compl concept const consteval constexpr constinit const_cast continue co_await co_return co_yield "
                + "decltype default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long "
                + "mutable namespace new noexcept not not_eq nullptr operator or or_eq private protected public reflexpr register reinterpret_cast "
                + "requires return short signed sizeof static static_assert static_cast struct switch synchronized template this thread_local throw "
                + "true try typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq "
                + "_int8 _int16 _int32 _int64 _int128 __int8 __int16 __int32 __int64 __int128 __declspec __cdecl __stdcall __fastcall __vectorcall __thiscall NULL"
            ).Split(' '),
            StringComparer.Ordinal
        );

        internal static string FieldName(string name)
        {
            var identifier = name.ToCIdentifier();
            return FieldKeywords.Contains(identifier) ? "field_" + identifier : identifier;
        }

        private StreamWriter writer;
        private readonly HashSet<TypeInfo> visited = [];
        private readonly HashSet<TypeInfo> visiting = [];
        private readonly HashSet<string> arrayForwards = [];
        private readonly HashSet<string> emittedArrays = [];
        private readonly HashSet<(int Definition, bool Split)> emittedVTables = [];
        private readonly HashSet<int> emittedInterfaceViews = [];
        private Dictionary<int, TypeInfo> canonicalLayouts;
        private Il2CppInspector Package => native.Package;

        internal void Write(string path)
        {
            new ZzzJsonMetadata(model).PrepareNativeArrayTypes();
            using var output = new StreamWriter(path, false, Encoding.UTF8);
            writer = output;
            writer.WriteLine(
                """
                // Generated by Il2CppInspector: ZenlessZoneZero 3.2.0 Windows MORAX
                typedef unsigned char uint8_t;
                typedef unsigned short uint16_t;
                typedef unsigned int uint32_t;
                typedef unsigned long long uint64_t;
                typedef signed char int8_t;
                typedef short int16_t;
                typedef int int32_t;
                typedef long long int64_t;
                typedef uint64_t uintptr_t;
                typedef int64_t intptr_t;
                typedef uint64_t size_t;
                #if !defined(_IDA_) && !defined(_GHIDRA_) && !defined(_BINARYNINJA_)
                #define _CPLUSPLUS_
                #endif
                """
            );
            if (useBetterArraySize)
            {
                writer.WriteLine("#define il2cpp_array_size_t actual_il2cpp_array_size_t");
            }

            writer.WriteLine(headers.GetTypeHeaderText(64));
            if (useBetterArraySize)
            {
                writer.WriteLine("#undef il2cpp_array_size_t\ntypedef union { int32_t size; actual_il2cpp_array_size_t value; } il2cpp_array_size_t;");
            }

            var types = native.Model.TypesByDefinitionIndex.Where(t => t != null && t.Name != "<Module>").Concat(native.GenericTypes.Values).Distinct().ToArray();
            foreach (var type in types)
            {
                var name = native.Name(type);
                if (!type.IsEnum)
                {
                    writer.WriteLine($"struct {name};");
                }

                writer.WriteLine($"struct {name}__Class; struct {name}__Boxed;");
            }
            foreach (var type in types.Where(t => t.IsEnum))
            {
                EmitEnum(type);
            }

            WriteArrayForwards();
            foreach (var type in types)
            {
                Emit(type);
            }

            while (emittedArrays.Count < native.ArrayTypes.Count)
            {
                foreach (var (name, type) in native.ArrayTypes.ToArray())
                {
                    if (!emittedArrays.Add(name))
                    {
                        continue;
                    }

                    var element = type.ElementType;
                    if (element.IsValueType && !element.IsPrimitive && !element.IsEnum)
                    {
                        Emit(element);
                    }

                    var elementStorage = native.CType(element);
                    WriteArrayForwards();
                    writer.WriteLine($"// {type.CSharpName}; vector follows the 32-byte array header.");
                    writer.WriteLine($"struct {name} {{ Il2CppClass *klass; void *monitor; Il2CppArrayBounds *bounds; il2cpp_array_size_t max_length; {elementStorage} vector[32]; }};");
                }
            }
            // The stock scaffolding helpers refer to app::String.
            writer.WriteLine($"#ifdef _CPLUSPLUS_\nnamespace app {{ using String = ::{native.Name(native.Model.TypesByFullName["System.String"])}; }}\n#endif");
        }

        private void WriteArrayForwards()
        {
            foreach (var name in native.ArrayTypes.Keys)
            {
                if (arrayForwards.Add(name))
                {
                    writer.WriteLine($"struct {name};");
                }
            }
        }

        private void Emit(TypeInfo type)
        {
            if (visited.Contains(type))
            {
                return;
            }

            if (!visiting.Add(type))
            {
                throw new InvalidDataException("Cyclic ZZZ value-type layout.");
            }

            var definition = type.Definition.IsValid ? type.Definition : type.GetGenericTypeDefinition().Definition;
            var group = type.IsEnum ? Adapter.DefinitionLayoutGroup(type.GetEnumUnderlyingType().Index) : type.GameLayoutGroup ?? Adapter.DefinitionLayoutGroup(type.Index);
            var size = type.IsEnum ? type.GetEnumUnderlyingType().Sizes.InstanceSize : Adapter.LayoutSizes(group).InstanceSize;
            var name = native.Name(type);
            if (type.IsGenericType && !type.IsGenericTypeDefinition && !type.IsEnum && !type.GameLayoutGroup.HasValue)
            {
                // Missing object storage does not change the constructed class allocator's vtable layout.
                writer.WriteLine($"// {type.CSharpName}; no materialized instance layout in this build.");
                EmitClass(name, type, definition);
                visiting.Remove(type);
                visited.Add(type);
                return;
            }
            var fields = new List<(int Offset, int Width, string Type, string Name)>();
            var statics = new Dictionary<int, List<(int Offset, int Width, string Type, string Name)>>();
            var baseTypes = new List<TypeInfo>();
            for (var current = type; current != null; current = current.BaseType)
            {
                baseTypes.Add(current);
            }

            baseTypes.Reverse();
            var names = new HashSet<string>();
            foreach (var current in baseTypes)
            {
                if (current.IsGenericTypeDefinition && current != type)
                {
                    continue;
                }

                if (current != type && current.IsGenericType && !current.IsGenericTypeDefinition && !current.GameLayoutGroup.HasValue)
                {
                    continue; // Preserve the unknown base storage extent instead of assigning definition offsets to it.
                }

                foreach (var field in current.DeclaredFields)
                {
                    if (field.IsLiteral)
                    {
                        continue;
                    }

                    if (field.IsStatic && current != type)
                    {
                        continue;
                    }

                    var ft = field.FieldType;
                    if (ft == null)
                    {
                        continue;
                    }

                    if (ft.IsValueType && !ft.IsPrimitive && !ft.IsEnum && ft != type && !ft.ContainsGenericParameters && native.CType(ft) != "void *")
                    {
                        Emit(ft);
                    }

                    var ctype = native.CType(ft);
                    var width = Width(ft);
                    var offset = checked((int)field.Offset);
                    if (!field.IsStatic && !type.IsValueType)
                    {
                        offset -= 16;
                    }

                    var fieldName = FieldName(field.Name);
                    while (!names.Add(fieldName))
                    {
                        fieldName += "_" + field.Index;
                    }

                    if (offset < 0)
                    {
                        continue;
                    }

                    if (ft.IsValueType && !ft.ContainsGenericParameters && ctype == "void *" && width > 0)
                    {
                        // The extent is known but this constructed value has no emitted declaration.
                        ctype = "uint8_t";
                        fieldName += $"[{width}]";
                    }
                    var item = (offset, width, ctype, fieldName);
                    if (field.IsStatic)
                    {
                        var tag = field.ZzzStorageTag;
                        if (!statics.TryGetValue(tag, out var region))
                        {
                            statics.Add(tag, region = []);
                        }

                        region.Add(item);
                    }
                    else
                    {
                        fields.Add(item);
                    }
                }
            }
            for (var i = 0; i < fields.Count; i++)
            {
                var field = fields[i];
                if (field.Width != 0)
                {
                    continue;
                }

                var next = fields.Where(f => f.Offset > field.Offset).Select(f => f.Offset).DefaultIfEmpty(checked((int)Math.Max(0, (long)size - 16))).Min();
                var extent = Math.Max(0, next - field.Offset);
                fields[i] = (field.Offset, extent, "uint8_t", field.Name + $"[{extent}]");
            }
            // Open generic definitions have no instantiated storage. Pick one recovered materialized layout.
            if (type.IsGenericTypeDefinition)
            {
                canonicalLayouts ??= native.GenericTypes.Values.Where(t => !t.ContainsGenericParameters && t.GameLayoutGroup.HasValue).GroupBy(t => t.Index).ToDictionary(g => g.Key, g => g.First());
                canonicalLayouts.TryGetValue(type.Index, out var concrete);
                if (concrete != null)
                {
                    Emit(concrete);
                    writer.WriteLine($"// {type.CSharpName}; canonical materialized layout follows {native.Name(concrete)}.");
                    writer.WriteLine($"struct {name} {{ struct {native.Name(concrete)} storage; }};");
                    EmitClass(name, type, definition);
                    foreach (var current in baseTypes)
                    {
                        current.ReleaseGeneratedFields();
                    }

                    visiting.Remove(type);
                    visited.Add(type);
                    return;
                }
            }
            WriteArrayForwards();
            writer.WriteLine($"// {type.CSharpName}; instance_size=0x{size:X}, including the 16-byte object header.");
            writer.WriteLine("#pragma pack(push, 1)");
            var alignment = type.IsValueType ? $" __declspec(align({Adapter.LayoutAlignment(group)}))" : "";
            writer.WriteLine($"struct{alignment} {name}" + (type.IsValueType ? "" : "__Fields") + " {");
            WriteFields(fields, checked((int)Math.Max(0, (long)size - 16)));
            writer.WriteLine("};");
            if (type.IsValueType)
            {
                writer.WriteLine($"struct {name}__Boxed {{ struct {name}__Class *klass; void *monitor; struct {name} fields; }};");
            }
            else
            {
                writer.WriteLine($"struct {name} {{ struct {name}__Class *klass; void *monitor; struct {name}__Fields fields; }};");
            }

            foreach (var (tag, region) in statics.OrderBy(pair => pair.Key))
            {
                var suffix = tag switch
                {
                    0 => "__StaticFields",
                    1 => "__ThreadStaticFields",
                    _ => $"__GlobalStaticFields{tag}",
                };
                writer.WriteLine($"// Offsets relative to {ZzzAssemblyWriter.ZzzStorageBase((uint)tag)}.");
                writer.WriteLine($"struct {name}{suffix} {{");
                WriteFields(region, 0);
                writer.WriteLine("};");
            }
            writer.WriteLine("#pragma pack(pop)");
            EmitClass(name, type, definition);
            foreach (var current in baseTypes)
            {
                current.ReleaseGeneratedFields();
            }

            visiting.Remove(type);
            visited.Add(type);
        }

        private void EmitEnum(TypeInfo type)
        {
            var name = native.Name(type);
            var underlying = native.CType(type.GetEnumUnderlyingType());
            var names = new HashSet<string>();
            var fields = type
                .DeclaredFields.Where(f => f.IsLiteral)
                .Select(field =>
                {
                    var identifier = FieldName(field.Name);
                    while (!names.Add(identifier))
                    {
                        identifier += "_" + field.Index;
                    }

                    var value = field.DefaultValue ?? throw new InvalidDataException($"Missing enum constant: {type.CSharpName}.{field.Name}");
                    var literal =
                        underlying.StartsWith("int", StringComparison.Ordinal) && Convert.ToInt64(value, CultureInfo.InvariantCulture) < 0
                            ? Convert.ToInt64(value, CultureInfo.InvariantCulture) is long.MinValue
                                ? "(-9223372036854775807LL - 1)"
                                : Convert.ToString(value, CultureInfo.InvariantCulture)
                            : $"0x{Convert.ToUInt64(value, CultureInfo.InvariantCulture):X}ULL";
                    return (identifier, literal);
                })
                .ToArray();
            writer.WriteLine($"// {type.CSharpName}");
            writer.WriteLine($"#ifdef _CPLUSPLUS_\nenum class {name} : {underlying} {{");
            foreach (var (identifier, literal) in fields)
            {
                writer.WriteLine($"    {identifier} = {literal},");
            }

            writer.WriteLine($"}};\n#else\nenum {name}__Enum {{");
            foreach (var (identifier, literal) in fields)
            {
                writer.WriteLine($"    {name}_{identifier} = {literal},");
            }
            // Analysis parsers use the scalar alias so byte/short enums retain their storage width.
            writer.WriteLine($"}};\ntypedef {underlying} {name};\n#endif");
            writer.WriteLine($"#pragma pack(push, 1)\nstruct {name}__Boxed {{ struct {name}__Class *klass; void *monitor; {name} value; }};\n#pragma pack(pop)");
            EmitClass(name, type, type.Definition.IsValid ? type.Definition : type.GetGenericTypeDefinition().Definition);
            type.ReleaseGeneratedFields();
            visited.Add(type);
        }

        private void EmitClass(string name, TypeInfo type, Next.Metadata.Il2CppTypeDefinition definition)
        {
            var count = definition.VTableCount;
            if (type.IsInterface && definition.MethodCount > 0)
            {
                var view = $"Zzz_InterfaceVTable_{type.Index}";
                if (emittedInterfaceViews.Add(type.Index))
                {
                    // This callable view starts at the concrete class's interface offset; it is not an interface class allocation.
                    writer.WriteLine($"struct {view} {{ union {{ Il2CppMethodPointer methodPtr[{definition.MethodCount}]; struct {{");
                    for (var slot = 0; slot < definition.MethodCount; slot++)
                    {
                        var method = native.Model.MethodsByDefinitionIndex[definition.MethodIndex + slot];
                        if (method.Definition.Slot != slot)
                        {
                            throw new InvalidDataException("Unexpected ZZZ interface method slot ordering.");
                        }

                        writer.WriteLine($"    Il2CppMethodPointer methodPtr_{slot}_{FieldName(method.Name)};");
                    }
                    writer.WriteLine("}; }; };");
                }
                writer.WriteLine($"typedef struct {view} {name}__InterfaceVTable;");
                if (count == 0)
                {
                    writer.WriteLine($"typedef struct {view} {name}__VTable;");
                }
            }
            if (count == 0)
            {
                writer.WriteLine($"struct {name}__Class {{ Il2CppClass_0 header; }};");
                return;
            }
            // Constructed classes always allocate both arrays. Definitions do so only when a nonzero MethodRef occurs.
            var split = (type.IsGenericType && !type.IsGenericTypeDefinition) || Adapter.DefinitionHasSplitVTable(definition);
            var definitionIndex = type.Index;
            var sharedName = $"Zzz_VTable_{definitionIndex}_{(split ? "Dual" : "Single")}";
            if (!emittedVTables.Add((definitionIndex, split)))
            {
                WriteClass();
                return;
            }
            writer.WriteLine($"struct {sharedName} {{");
            var slots = new string[count];
            for (var slot = 0; slot < count; slot++)
            {
                var usage = MetadataUsage.FromEncodedIndex(Package, Package.VTableMethodIndices[definition.VTableIndex + slot]);
                var methodIndex = usage.Type switch
                {
                    MetadataUsageType.MethodDef when usage.IsValid => usage.SourceIndex,
                    MetadataUsageType.MethodRef when usage.IsValid => Package.MethodSpecs[usage.SourceIndex].MethodDefinitionIndex,
                    _ => -1,
                };
                slots[slot] = methodIndex < 0 ? "unknown" : FieldName(native.Model.MethodsByDefinitionIndex[methodIndex].Name);
            }
            WriteSlots("Il2CppMethodPointer", "methodPtr");
            if (split)
            {
                WriteSlots("const MethodInfo *", "method");
            }

            writer.WriteLine("};");
            WriteClass();

            void WriteClass()
            {
                writer.WriteLine($"typedef struct {sharedName} {name}__VTable;");
                writer.WriteLine($"struct {name}__Class {{ Il2CppClass_0 header; {name}__VTable vtable; }};");
            }

            void WriteSlots(string storage, string array)
            {
                writer.WriteLine($"    union {{ {storage} {array}[{count}]; struct {{");
                for (var slot = 0; slot < count; slot++)
                {
                    writer.WriteLine($"        {storage} {array}_{slot}_{slots[slot]};");
                }

                writer.WriteLine("    }; };");
            }
        }

        private int Width(TypeInfo type)
        {
            if (type.IsEnum)
            {
                return Width(type.GetEnumUnderlyingType());
            }

            if (!type.IsValueType || type.ContainsGenericParameters || type.IsPointer || type.IsByRef)
            {
                return 8;
            }

            var primitive = type.FullName switch
            {
                "System.Boolean" or "System.Byte" or "System.SByte" => 1,
                "System.Char" or "System.Int16" or "System.UInt16" => 2,
                "System.Int32" or "System.UInt32" or "System.Single" => 4,
                "System.Int64" or "System.UInt64" or "System.Double" or "System.IntPtr" or "System.UIntPtr" => 8,
                _ => 0,
            };
            if (primitive != 0)
            {
                return primitive;
            }

            return checked((int)Math.Max(0, (long)type.Sizes.InstanceSize - 16));
        }

        private void WriteFields(List<(int Offset, int Width, string Type, string Name)> fields, int size)
        {
            var sorted = fields.OrderBy(f => f.Offset).ToArray();
            var cursor = 0;
            var padding = 0;
            for (var i = 0; i < sorted.Length; )
            {
                var field = sorted[i];
                if (field.Offset > cursor)
                {
                    writer.WriteLine($"    uint8_t __padding_{padding++}[{field.Offset - cursor}];");
                }

                var end = field.Offset + field.Width;
                var j = i + 1;
                while (j < sorted.Length && sorted[j].Offset < end)
                {
                    end = Math.Max(end, sorted[j].Offset + sorted[j].Width);
                    j++;
                }
                if (j == i + 1)
                {
                    writer.WriteLine($"    {field.Type} {field.Name};");
                }
                else
                {
                    writer.WriteLine("    union {");
                    for (var n = i; n < j; n++)
                    {
                        var f = sorted[n];
                        if (f.Offset == field.Offset)
                        {
                            writer.WriteLine($"        {f.Type} {f.Name};");
                        }
                        else
                        {
                            writer.WriteLine($"        struct {{ uint8_t __padding_{padding++}[{f.Offset - field.Offset}]; {f.Type} {f.Name}; }};");
                        }
                    }
                    writer.WriteLine("    };");
                }
                cursor = Math.Max(cursor, end);
                i = j;
            }
            if (size > cursor)
            {
                writer.WriteLine($"    uint8_t __padding_{padding}[{size - cursor}];");
            }
        }
    }
}
