<Project>
  <Target Name="GetGamePluginOutput" Returns="@(GamePluginOutput)">
    <ItemGroup>
      <GamePluginOutput Include="$(TargetDir)**/*">
        <PluginDirectory>$([System.IO.Path]::GetFileName('$(MSBuildProjectDirectory)'))</PluginDirectory>
        <PluginSubdirectory>%(RecursiveDir)</PluginSubdirectory>
      </GamePluginOutput>
    </ItemGroup>
  </Target>
</Project>
